image: python:latest

clone:
  depth: full
  
pipelines:
  branches:
    master:
      - step:
          caches:
            - pip
          script:
            - pip install -r requirements.txt
      - step:
                name: Deploy to Heroku
                deployment: staging #production
                script:
                  - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
                  - heroku ps:scale web=1